### ISSUE TITLE
Scatter and spell batching interactions with charge

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/classic-hunter#17]
On pservers, if you're fast enough (I mean insanely fast or just good judge) you can scatter an enemy charge, preventing them from ever getting to you. Is this possible on the beta? Is it even easier on the beta? Does the increased window from spell batching make it more responsive or do you still get stunned and they travel to you but get scattered at the spot they charged to?

**Comment by Zarant** [comment]
I played hunter for years, and I remember when that happened, the warrior would charge to your position and then slowly wander off to the location they were before charging, I tried to find old videos to corroborate that but so far I'm not successful.

**Comment by watchyoursixx** [comment]
I tested several times near the end of beta and it seemed a lot harder to get this timing down...

**Comment by watchyoursixx** [comment]
It's still possible however very reliant on resisting the stun as it is applied in the same instant the warrior starts to charge.
